In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
results = pd.DataFrame({

    "Version": [

        "Vision V1",
        "Vision V2",
        "Vision V3"

    ],

    "IoU": [

        0.5715,
        0.6227,
        0.6887

    ],

    "Dice Score": [

        0.7213,
        0.7629,
        0.8132

    ],

    "Pixel Accuracy": [

        0.8148,
        0.8280,
        0.8646

    ]

})

results

     Version     IoU  Dice Score  Pixel Accuracy
0  Vision V1  0.5715      0.7213          0.8148
1  Vision V2  0.6227      0.7629          0.8280
2  Vision V3  0.6887      0.8132          0.8646

In [4]:
results["IoU Improvement"] = (
    results["IoU"].diff()
)

results["Dice Improvement"] = (
    results["Dice Score"].diff()
)

results["Accuracy Improvement"] = (
    results["Pixel Accuracy"].diff()
)

results

,Version,IoU,Dice Score,Pixel Accuracy,IoU Improvement,Dice Improvement,Accuracy Improvement
0,Vision V1,0.5715,0.7213,0.8148,NaN,NaN,NaN
1,Vision V2,0.6227,0.7629,0.8280,0.0512,0.0416,0.0132
2,Vision V3,0.6887,0.8132,0.8646,0.0660,0.0503,0.0366

In [5]:
best = results.loc[
    results["IoU"].idxmax()
]

best

Version                 Vision V3
IoU                        0.6887
Dice Score                 0.8132
Pixel Accuracy             0.8646
IoU Improvement             0.066
Dice Improvement           0.0503
Accuracy Improvement       0.0366
Name: 2, dtype: object

In [6]:
changes = pd.DataFrame({

    "Version":[

        "Vision V1",
        "Vision V2",
        "Vision V3"

    ],

    "Major Changes":[

        "Baseline UNet",

        "Data Augmentation\nLearning Rate Scheduler\nBCE + Dice Loss",

        "BatchNorm\nEarly Stopping\nGradient Clipping\nIoU Tracking"

    ]

})

changes

     Version                                      Major Changes
0  Vision V1                                      Baseline UNet
1  Vision V2  Data Augmentation\nLearning Rate Scheduler\nBC...
2  Vision V3  BatchNorm\nEarly Stopping\nGradient Clipping\n...